# logging config
project: set_tracking
logdir: /global/cfs/cdirs/m3443/usr/ryanliu/set_tracking/transformer-single-gpu

# trainer config
accelerator: gpu
devices: 1
nodes: 1
workers: 32
train_batches: 10000
val_batches: 1000
max_epochs: 100
batch_size: 16
warmup: 1000
lr: 0.001
patience: 100
factor: 1
t0: 50
curriculum: np.clip(1.2 * t - 0.2, a_min=0.1, a_max=1)

# model config
model: Transformer
d_model: 128
d_ff: 256
heads: 8
n_layers: 12
n_pool_layer: 2
dropout: 0.

# dataset config
dataset_args:
    hole_inefficiency: 0.
    d0: 0.1
    noise: 0.
    num_particles: 1
    pt_dist: [2.5, 2.6]
    min_radius: 0.5
    max_radius: 3.