# logging config
project: PJEPA
logdir: /global/cfs/cdirs/m3443/usr/ryanliu/JEPA

# trainer config
accelerator: gpu
devices: 1
nodes: 1
workers: 32
train_batches: 10000
val_batches: 1000
max_epochs: 100
batch_size: 16
warmup: 1000
lr: 0.002
patience: 100
factor: 1

# model config
model: JEPA
d_model: 128
d_ff: 256
heads: 8
n_layers: 6
n_agg_layers: 2
n_predictor_layers: 4
num_gaussians: 50
ema_decay: 0.999
dropout: 0.

# dataset config
dataset_args:
    hole_inefficiency: 0.1
    d0: 0.1
    noise: 0.1
    minbias_lambda: 100
    pileup_lambda: 95
    hard_proc_lambda: 5
    minbias_pt_dist: [1, 5]
    pileup_pt_dist: [1, 5]
    hard_proc_pt_dist: [100, 5, normal]